runtime: java
env: flex
runtime_config:
  jdk: openjdk8
manual_scaling:
  instances: 1
resources:
  memory_gb: 2.3
handlers:
- url: /.*
  script: this field is required, but ignored
readiness_check:
  app_start_timeout_sec: 600